version: 2

builds:
  - id: multipass
    main: ./cmd/multipass
    binary: multipass
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - config.example.yaml
      - config.oidc.yaml

checksum:
  name_template: checksums.txt

release:
  replace_existing_artifacts: true

source: {}

changelog:
  disable: true